-- Create User Preferences Table
CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency VARCHAR(255),
    timezone VARCHAR(255),
    email_notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    sms_notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create User Table
CREATE TABLE nestuity_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    password_hash VARCHAR(255),
    auth_provider VARCHAR(255) NOT NULL DEFAULT 'credentials',
    provider_id VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    is_active BOOLEAN NOT NULL,
    preferences_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_user_preferences FOREIGN KEY (preferences_id) REFERENCES user_preferences(id)
);

-- Create Baby Table
-- Note: Baby uses @GeneratedValue without strategy in code, which usually defaults to a sequence in Hibernate for Postgres.
-- However, for consistency and simplicity in migration, we'll use IDENTITY or a SEQUENCE.
-- If the existing DB used 'update', it likely created a sequence 'baby_seq'.
-- To be safe and modern, we'll use IDENTITY, but if there's legacy data with a sequence, this might need adjustment.
-- Given this is a "reseedable" dev DB mostly, IDENTITY is fine.
CREATE TABLE baby (
    id BIGINT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date_of_birth TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    weight DOUBLE PRECISION,
    diaper_size VARCHAR(255),
    daily_usage INTEGER DEFAULT 0,
    CONSTRAINT fk_baby_user FOREIGN KEY (user_id) REFERENCES nestuity_user(id)
);

-- Create sequence for Baby if not using IDENTITY (matching Hibernate default behavior for @GeneratedValue)
CREATE SEQUENCE IF NOT EXISTS baby_seq START WITH 1 INCREMENT BY 50;

-- Create Inventory Table
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    supply_name VARCHAR(255) NOT NULL,
    total_single_quantity DOUBLE PRECISION NOT NULL,
    total_unit_quantity DOUBLE PRECISION NOT NULL,
    unit_conversion DOUBLE PRECISION NOT NULL,
    preferred_supply_min INTEGER NOT NULL DEFAULT 14,
    CONSTRAINT fk_inventory_user FOREIGN KEY (user_id) REFERENCES nestuity_user(id)
);

-- Create Baby Product Table
CREATE TABLE baby_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    category VARCHAR(255),
    description TEXT,
    currency VARCHAR(10),
    in_stock BOOLEAN,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create Price History Table
CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baby_product_id BIGINT NOT NULL,
    retailer VARCHAR(255) NOT NULL,
    product_url VARCHAR(2048),
    price NUMERIC(10, 2) NOT NULL,
    date TIMESTAMP NOT NULL,
    CONSTRAINT fk_price_history_product FOREIGN KEY (baby_product_id) REFERENCES baby_product(id)
);
